version: '3.9'

services:
  main_todolist_db:
    image: postgres
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=todolist
volumes:
  todolist_postgres_data: