version: '3.8'

services:
  main_todolist_db:
    image: postgres:12.4-alpine
    volumes:
      - todolist_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=todolist