version: '3.9'
services:

  db:
    env_file:
      - .env
    image: postgres:14
    container_name: db-1
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    healthcheck:
      #test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5


volumes:
  data:
    external: true
    name: ./docker/postgres



